# site properties and page defaults
title: "Kaikkonen Lab"
subtitle: "Cardiovascular Epigenomics and Gene Regulation"
header: "images/cadgen.png"
footer: "images/uef_background.jpg"
logo-text: true
show-title: true
show-subtitle: true
